name: Build and Release APK

on:
  push: # Dispara o workflow em qualquer commit
    branches:
      - '**' # Permite buildar em qualquer branch

jobs:
  build:
    name: Build and Release APK
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout
        uses: actions/checkout@v3

      # Configuração do Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '<flutter_version>' # Substitua pela versão do Flutter, por exemplo: 3.13.0

      # Instalar dependências
      - name: Install Dependencies
        run: flutter pub get

      # Build do APK
      - name: Build APK
        run: flutter build apk --release

      # Criação da release no GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }} # Usar o SHA do commit como tag
          release_name: "Build from commit ${{ github.sha }}" # Nome da release
          body: |
            Build gerado automaticamente para o commit:
            - Branch: ${{ github.ref_name }}
            - Commit: ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Fazer upload do APK na release
      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release-${{ github.sha }}.apk
          asset_content_type: application/vnd.android.package-archive
